# Generated by Django 5.1.1 on 2024-10-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nombre_de_produit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Nombre de produits'),
        ),
    ]
