# Generated by Django 5.1.1 on 2024-10-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_nombre_de_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nombre_de_produit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de produits'),
        ),
    ]
