# Generated by Django 5.1.1 on 2024-10-09 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_nombre_de_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du fournisseur')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code du fournisseur')),
                ('email', models.EmailField(max_length=100, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
            ],
            options={
                'verbose_name': 'Fournisseur',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Offline'), (1, 'Online'), (2, 'Out of stock')], default=0, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='ProductFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_fournisseur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix fournisseur')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur', verbose_name='Fournisseur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Fournisseur Produit',
                'unique_together': {('product', 'fournisseur')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='fournisseurs',
            field=models.ManyToManyField(related_name='products', through='app.ProductFournisseur', to='app.fournisseur', verbose_name='Fournisseurs'),
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('price_in_store', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix en magasin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Inventaire Magasin',
                'unique_together': {('product',)},
            },
        ),
    ]
