# Generated by Django 5.1.1 on 2024-10-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_nombre_de_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du fournisseur')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code du fournisseur')),
                ('email', models.EmailField(max_length=100, verbose_name='Adresse email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Site web')),
                ('produits', models.ManyToManyField(related_name='fournisseurs', to='app.product', verbose_name='Produits fournis')),
            ],
            options={
                'verbose_name': 'Fournisseur',
            },
        ),
    ]
