# Generated by Django 5.1.2 on 2024-10-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fournisseur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='produits',
        ),
        migrations.AddField(
            model_name='product',
            name='fournisseur',
            field=models.ManyToManyField(related_name='products', to='app.fournisseur', verbose_name='Fournisseur'),
        ),
    ]
