# Generated by Django 5.1.1 on 2024-10-09 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fournisseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomEtat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_du_produit', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date création')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('etat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.etat')),
            ],
            options={
                'verbose_name': 'Commande',
                'unique_together': {('fournisseur', 'produit')},
            },
        ),
    ]
