# Generated by Django 5.1.2 on 2024-10-09 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_etat_commande'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseur',
            name='produits',
        ),
    ]
