# Generated by Django 5.1.2 on 2024-10-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_fournisseur_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_in_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('price_in_store', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Prix en magasin')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Inventaire Magasin',
                'unique_together': {('product',)},
            },
        ),
    ]
