# Generated by Django 5.1.2 on 2024-10-09 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_storeinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFournisseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_fournisseur', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix fournisseur')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur', verbose_name='Fournisseur')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Fournisseur Produit',
                'unique_together': {('product', 'fournisseur')},
            },
        ),
    ]
