# Generated by Django 5.1.2 on 2024-10-11 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_productfournisseur'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='storeinventory',
            name='fournisseur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur', verbose_name='Fournisseur'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together={('product', 'fournisseur')},
        ),
    ]
