# Generated by Django 5.1.1 on 2024-10-16 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_storeinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='storeinventory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='commande',
            name='fournisseur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.fournisseur'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='produit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.RemoveField(
            model_name='storeinventory',
            name='fournisseur',
        ),
    ]
