# Generated by Django 5.1.1 on 2024-10-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_storeinventory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commande',
            unique_together=set(),
        ),
    ]
