# Generated by Django 5.1.1 on 2024-10-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_commande_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nombre_de_produit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ttc',
        ),
    ]
