# Generated by Django 5.1.2 on 2024-10-16 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_commande_fournisseur_alter_commande_produit_and_more'),
        ('app', '0011_alter_commande_unique_together'),
    ]

    operations = [
    ]
