# Generated by Django 5.1.1 on 2024-10-16 16:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_merge_20241016_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='nombre_de_produit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ht',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_ttc',
        ),
        migrations.AlterField(
            model_name='product',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date création'),
        ),
    ]
